spring:
  application:
    name: Process orders
  datasource:
    url: jdbc:h2:mem:orders
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8088
